spring.application.name=fruits

# Razorpay API Keys (Test mode)
razorpay.key.id=rzp_test_VIdto8Snwz94lt
razorpay.key.secret=kzLTPSLqNr2tBGKztA9GgjaV


spring.mvc.view.prefix=/jsp/
spring.mvc.view.suffix=.jsp

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/fruit
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

